variables:
    SolutionBaseName: 'DFC.ServiceTaxonomy'
    BuildPlatform: 'any cpu'
    BuildConfiguration: 'release'

pool:
  name: NCS - CI and CD
  demands:
  - msbuild
  - visualstudio

resources:
  repositories:
  - repository: self
  - repository: dfc-devops
    type: github
    name: SkillsFundingAgency/dfc-devops
    ref: refs/tags/v1.11.1
    endpoint: 'GitHub (ESFA)'

stages:
- stage: Build
  jobs:
  - job: Build
    workspace:
      clean: all
    steps:
    - template: AzureDevOpsTemplates/Build/StepTemplates/dfc-dotnetcore-build-notests.yml@dfc-devops
      parameters:
        SolutionBaseName: $(SolutionBaseName).FunctionalTests
        BuildPlatform: $(BuildPlatform)
        BuildConfiguration: $(BuildPlatform)
        DotNetCoreVersion: 3.1.x