variables:
    SolutionBaseName: 'DFC.ServiceTaxonomy'

pool:
  name: NCS - CI and CD
  demands:
  - msbuild
  - visualstudio

resources:
  repositories:
  - repository: self
  - repository: dfc-devops
    type: github
    name: SkillsFundingAgency/dfc-devops
    ref: refs/tags/v1.11.0
    endpoint: 'GitHub (ESFA)'

stages:
- stage: Build
  jobs:
  - job: Build
    workspace:
      clean: all
    steps:
    - template: AzureDevOpsTemplates/Build/StepTemplates/dfc-dotnetcore-build-notests.yml@dfc-devops
      parameters:
        SolutionBaseName: $(SolutionBaseName).TestSuite