variables:
    SolutionBaseName: 'DFC.Composite.Shell'
    BuildPlatform: 'any cpu'
    BuildConfiguration: 'release'

resources:
  repositories:
  - repository: self
  - repository: dfc-devops
    type: github
    name: SkillsFundingAgency/dfc-devops
    ref: refs/tags/v1.6.5
    endpoint: 'GitHub (ESFA)'