variables:
    SolutionBaseName: 'DFC.ServiceTaxonomy.Tests'
    BuildPlatform: 'any cpu'
    BuildConfiguration: 'release'

resources:
  repositories:
  - repository: self
  - repository: dfc-devops
    type: github
    name: SkillsFundingAgency/dfc-devops
    ref: refs/tags/v1.11.1
    endpoint: 'GitHub (ESFA)'

stages:
- stage: Build
  jobs:
  - job: Build
    steps:
    - template: StepTemplates/dfc-dotnetcore-build-notests.yml
      parameters:
        SolutionBaseName: $(SolutionBaseName)
        BuildPlatform: $(BuildPlatform)
        BuildConfiguration: $(BuildPlatform)