variables:
    SolutionBaseName: 'DFC.ServiceTaxonomy'

pool:
  name: NCS - CI and CD
  demands:
  - msbuild
  - visualstudio

resources:
  repositories:
  - repository: self
  - repository: dfc-devops
    type: github
    name: SkillsFundingAgency/dfc-devops
    ref: refs/tags/v1.11.0
    endpoint: 'GitHub (ESFA)'

stages:
- stage: Build
  jobs:
  - job: Build
    workspace:
      clean: all
    steps:
    - task: DotNetCoreCLI@2
      displayName: 'Publish $(SolutionBaseName).TestSuite tests'
      inputs:
        command: 'publish'
        projects: '$(SolutionBaseName).TestSuite\$(SolutionBaseName).TestSuite.csproj'
        arguments: '-o "$(build.artifactstagingdirectory)\Artifact\$(SolutionBaseName).TestSuite"'
        publishWebProjects: False
        zipAfterPublish: true
    - task: PublishPipelineArtifact@1
      displayName: 'Publish Artifact: $(SolutionBaseName).TestSuite'
      inputs:
        targetPath: $(build.artifactstagingdirectory)\Artifact\$(SolutionBaseName).TestSuite\
        artifactName: $(SolutionBaseName).TestSuite.DeploymentPackages